repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      # lint
      - id: ruff
        types_or: [ python ]
        language: python
      # format
      - id: ruff-format
        types_or: [ python ]

  - repo: local
    hooks:
      - id: frontend-build
        name: frontend build
        entry: bash -c 'cd frontend && npm run build'
        language: system
        files: ^frontend/
        types_or: [ts, tsx]
        pass_filenames: false
