name: CI

x-ignore-patterns: &ignore-patterns
  - 'notes/**'
  - 'docs/**'
  - '**/*.md'
  - '**/*.rst'
  - '**/*.txt'
  - '**/*.ipynb'
  - '**/*.{png,jpg,svg}'

on:
  push:
    branches: [ main ]
    paths-ignore: *ignore-patterns
  pull_request:
    paths-ignore: *ignore-patterns

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build cpu image, gateway
        run: docker compose build --parallel kokoro-cpu-worker gateway
